### ISSUE TITLE
Nanobind does not support fields of opaque references

### ISSUE THREAD

**Issue by tyler-zeromatter** [rust-diplomat/diplomat#1107]
Tests are failing in https://github.com/rust-diplomat/diplomat/pull/1106 because the Nanobind backend seemingly does not support structs holding references to opaques (i.e., `const Opaque&`)

**Comment by tyler-zeromatter** [comment]
Looking into this further, will update as I diagnose the issue.

**Comment by tyler-zeromatter** [comment]
Seems like if `StructOfOpaque::op` is `MyOpaque&`, then the compiler does not like the bound `.def_rw("op", &StructOfOpaque::op)`. In MSVC I get `error C2634: 'somelib::StructOfOpaque::op': pointer to reference member is illegal`

**Comment by tyler-zeromatter** [comment]
Ah, there's technically already a fix, but it doesn't track references. Will make a PR

**Comment by tyler-zeromatter** [comment]
So, this is a problem directly related to the issues in #1102. Because we rely on the C++ backend, opaques in structs are `Opaque&`. We are not allowed to rebind opaques in structs as long as we continue to rely on the C++ backend (AFAIK).

There are two options here:

1. Disable any *references* to opaques in structs for Nanobind (boxed for out types only is still fine). This would be a backend specific panic.
2. Make all properties with references in Nanobind read-only.
3. Modify the C++ generation output just in Nanobind to store references as pointers (I think this one is out just because of how complicated and unnecessary it would be)

Option 2 would work okay, but the existing solution is itself already kind of hacky (it checks strings for `std::unique_ptr` rather than type behavior), and it's no good for if you want to create a struct yourself and pass it in from Python. So I think for now option 1 is what I'll go with for the PR.

**Comment by tyler-zeromatter** [comment]
This is just a symptom of #1110, closing as duplicate.
