### PR TITLE
Make C2TyGenContext public

### PR DESCRIPTION
**Pull request by Manishearth**
Otherwise this fails to compile on Rust 1.70 (ICU4X MSRV)

```
error[E0446]: crate-private type `c2::ty::TyGenContext<'ccx, 'tcx>` in public interface
   --> /home/runner/.cargo/git/checkouts/diplomat-6c8ebb579fc79396/656fd0a/tool/src/cpp2/ty.rs:126:5
    |
126 |     pub c: C2TyGenContext<'ccx, 'tcx>,
    |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ can't leak crate-private type
    |
   ::: /home/runner/.cargo/git/checkouts/diplomat-6c8ebb579fc79396/656fd0a/tool/src/c2/ty.rs:111:1
    |
111 | pub(crate) struct TyGenContext<'cx, 'tcx> {
    | ----------------------------------------- `c2::ty::TyGenContext<'ccx, 'tcx>` declared as crate-private
```

### CODE REVIEW

**Comment by robertbastian** [comment]
Why does the field need to be public?

**Comment by robertbastian** [comment]
I did this in #506
